# Generated by Django 2.2.7 on 2020-07-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0003_invester_services_related_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('review', models.TextField()),
            ],
        ),
    ]
