# Generated by Django 2.2.7 on 2020-07-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0004_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='acts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
