# Generated by Django 2.2.7 on 2020-07-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0005_acts_rules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acts',
            new_name='g_acts',
        ),
    ]
