# Generated by Django 2.2.7 on 2020-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0006_auto_20200712_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='g_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulars', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
