# Generated by Django 2.2.7 on 2020-07-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0007_g_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='g_policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
