# Generated by Django 3.0.8 on 2020-08-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0009_left_notification_right_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic_schemes',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
