# Generated by Django 3.0.8 on 2020-08-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains', '0010_auto_20200802_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dic_schemes',
            name='url',
        ),
        migrations.RemoveField(
            model_name='rural_schemes',
            name='url',
        ),
        migrations.AddField(
            model_name='dic_schemes',
            name='document',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rural_schemes',
            name='document',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
